#Input Parameters:
#   X86T_C_FLAGS                      - C compiler flags
#   X86T_C_SOURCES                    - C source files
#   X86T_ASM_NASM_FLAGS               - nasm assembler flags
#   X86T_ASM_NASM_BINARY_SOURCES      - nasm source file to build an executable from
#   X86T_ASM_NASM_SOURCES             - nasm source files
#   X86T_AUTOGENERATED_OUTPUT_SOURCES - autogenerated source files

#Otherwise gcc is tried
set(CMAKE_ASM_NASM_LINK_EXECUTABLE "ld <FLAGS> <CMAKE_ASM_NASM_LINK_FLAGS> <LINK_FLAGS> <OBJECTS>  -o <TARGET> <LINK_LIBRARIES>")

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${X86T_C_FLAGS}")

set_source_files_properties(${X86T_ASM_NASM_SOURCES} ${X86T_ASM_NASM_BINARY_SOURCES} PROPERTIES LANGUAGE ASM_NASM)
set(CMAKE_ASM_NASM_COMPILE_OBJECT "${CMAKE_ASM_NASM_COMPILE_OBJECT} ${X86T_ASM_NASM_FLAGS}")

add_executable(bin_asm ${X86T_ASM_NASM_BINARY_SOURCES})
set_target_properties(bin_asm PROPERTIES LINKER_LANGUAGE ASM_NASM)

add_executable(bin ${X86T_C_SOURCES} ${X86T_AUTOGENERATED_OUTPUT_SOURCES} ${X86T_ASM_NASM_SOURCES})
set_target_properties(bin PROPERTIES LINKER_LANGUAGE C)

target_include_directories(bin PRIVATE include)
#target_include_directories(bin_asm PRIVATE include)