file(MAKE_DIRECTORY ${X86T_AUTOGENERATED_SRC_DIR_ASM_NASM_INC})

function(JOIN VALUES GLUE OUTPUT)
  string (REGEX REPLACE "([^\\]|^);" "\\1${GLUE}" _TMP_STR "${VALUES}")
  string (REGEX REPLACE "[\\](.)" "\\1" _TMP_STR "${_TMP_STR}") #fixes escaping
  set (${OUTPUT} "${_TMP_STR}" PARENT_SCOPE)
endfunction()

JOIN("${X86T_AUTOGENERATED_SRC_DIR_ASM_NASM_INC}" ":" X86T_AUTOGENERATED_SRC_DIR_ASM_NASM_INC_JOINED)
message(${X86T_AUTOGENERATED_SRC_DIR_ASM_NASM_INC_JOINED})

#TODO: Add check that python3.7 is installed
#TODO: Make it return a colon-separated pair of c_header_input:asm_nasm_inc_output
execute_process(
    COMMAND python3.7 ${CMAKE_CURRENT_SOURCE_DIR}/generate_source_paths.py \
        --headers-c-to-nasm ${X86T_AUTOGENERATED_SRC_DIR_ASM_NASM_INC_JOINED} \
        --nasm-include-dir ${X86T_AUTOGENERATED_SRC_DIR_ASM_NASM_INC}
    OUTPUT_VARIABLE X86T_AUTOGENERATED_OUTPUT_FILES
)

#TODO: Add check that python3.7 is installed
add_custom_command(
    OUTPUT ${X86T_AUTOGENERATED_OUTPUT_FILES} 
    COMMAND python3.7 ${CMAKE_CURRENT_SOURCE_DIR}/cnasm_conv.py ${X86T_AUTOGENERATED_OUTPUT_FILES} 
    DEPENDS 
)